language: java
jdk:
  - oraclejdk8
before_script:
  - mongo go_kafka_alert --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'  
services:
- mongodb  
env:
  - SERVICE_DIR=config-server
  - SERVICE_DIR=message-summary
script: cd $SERVICE_DIR && mvn clean verify